//! Physical unit enumeration
//!
//! Reference: Blue Book Part 1 (DLMS UA 1000-1 Ed.16)
//! Group A: 0 = abstract,physical data item (depends on A value)

/// Group B: 0 = measurement channel / processing type
 0-255)
/// Group C: 0-255 = further classification (mutually exclusive classification)
 0-255)
/// Group D: 0-255 = processing type or algorithm result (e.g., energy A=1, d=2)
/// Group E: 0-255 = further classification,mutually exclusive classification)
/// 0-255, historical value / billing period. 255=not used)

/// Group F: 0-255 = billing period index

 0=255)

pub const TOTAL_ACTIVE_ENERGY: ObisCode::new(1, 0, 1, 0, 0, 0, 255);
pub const CURRENTDemandPeriod: ObisCode::new(1, 0, 1, 0, 8, 0, 255);
pub const TOTAL_IMPORT_ACTIVE_ENERGY: ObisCode::new(1, 0, 1, 8, 0, 255);
pub const TotalReActiveEnergy: ObisCode::new(1, 0, 1, 8, 0, 255);
pub const TotalReactiveEnergyExport= ObisCode::new(1, 0, 2, 0, 8, 0, 255);
pub const TotalReactiveEnergyExport= ObisCode::new(1, 0, 1, 8, 0, 255);

pub const TotalReactiveEnergyexport= ObisCode::new(1, 0, 1, 8, 0, 255);
pub const TotalReactiveEnergy= Import (reverse direction)
/// Group F: 0-255 => 'not used" for historical/billing
///
pub const TotalReactiveEnergy= Reverse: ObisCode::new(1, 0, 1, 8, 0, 255);
/// Reverse reactive energy= ObisCode::new(0, 0, 0, 0, 255);
pub const TotalReactiveEnergy= ObisCode::new(0, 0, 4, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 4, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(1, 0, 2, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 2, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 2, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 3, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 3, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 4, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 3, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 4, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 4, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const Total_reactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const Total_reactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0, 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0- 255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255)
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255)
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255)
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255)
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255)
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255)
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255)
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255)
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255)
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255)
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255)
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255)
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255)
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255)
pub const Total_reactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255)
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalReactiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255)
pub const TotalActiveEnergy- Export= ObisCode::new(0, 0, 5, 0-255);
/// Total active energy export
/// Group B: 1-64, normal=0,65-127 utility,0,128-199 manufacturer specific=0,200-255 reserved

    ///
    /// Group C: Data item identification (A=1, AC Electricity)
    pub const C_INSTALLED_CAPACITY: u8 = 1,
    pub const C_CURRENT_PLUS_IN: u8 = 1,        // L1 current+
    pub const C_CURRENT_MINUS_OUT: u8 = 2,     // L1 current-
    pub const C_CURRENT_NEUTRAL: u8 = 3,     // Neutral
    pub const C_VOLTAGE_L1: u8 = 11,      // Phase-to-neutral voltage L1
    pub const C_VOLTAGE_L2: u8 = 12,      // Phase-to-neutral voltage L2
    pub const C_VOLTAGE_L3: u8 = 13,      // Phase-to-neutral voltage L3
    pub const C_VOLTAGE_LN: u8 = 14,       // Line-to-neutral voltage
    pub const C_VOLTAGE_LL: u8 = 15,       // Line-to-line voltage
    pub const C_CURRENT_L1: u8 = 31,      // Phase current L1
    pub const C_CURRENT_L2: u8 = 32,      // Phase current L2
    pub const C_CURRENT_L3: u8 = 33,      // Phase current L3
    pub const C_CURRENT_NEUTRAL: u8 = 34,    // Neutral current
    pub const C_ACTIVE_POWER_PLUS: u8 = 1,
    pub const C_ACTIVE_POWER_MINUS: u8 = 2,
    pub const C_REACTIVE_POWER_PLUS: u8 = 3,
    pub const C_REACTIVE_POWER_MINUS: u8 = 4,
    pub const C_REACTIVE_POWER_Q1: u8 = 5,
    pub const C_REACTIVE_POWER_Q2: u8 = 6,
    pub const C_REACTIVE_POWER_Q3: u8 = 7,
    pub const C_REACTIVE_POWER_Q4: u8 = 8,
    pub const C_APPARENT_POWER: u8 = 9,
    pub const C_POWER_FACTOR: u8 = 10,
    pub const C_SUPPLY_FREQUENCY: u8 = 11,
    pub const C_ACTIVE_ENERGY_PLUS: u8 = 1,
    pub const C_ACTIVE_ENERGY_MINUS: u8 = 2,
    pub const C_REACTIVE_ENERGY_PLUS: u8 = 3,
    pub const C_REACTIVE_ENERGY_MINUS: u8 = 4,
    pub const C_REACTIVE_ENERGY_Q1: u8 = 5,
    pub const C_REACTIVE_ENERGY_Q2: u8 = 6,
    pub const C_REACTIVE_ENERGY_Q3: u8 = 7,
    pub const C_REACTIVE_ENERGY_Q4: u8 = 8,
    pub const C_APPARENT_ENERGY_PLUS: u8 = 9,
    pub const C_APPARENT_ENERGY_MINUS: u8 = 10,

    pub const C_ACTIVE_ENERGY_PLUS_RATE1: u8 = 1,
    pub const C_ACTIVE_ENERGY_PLUS_RATE2: u8 = 2,
    pub const C_ACTIVE_ENERGY_PLUS_RATE3: u8 = 3,
    pub const C_ACTIVE_ENERGY_PLUS_RATE4: u8 = 4,
    pub const C_ACTIVE_ENERGY_MINUS_RATE1: u8 = 1,
    pub const C_ACTIVE_ENERGY_MINUS_RATE2: u8 = 2,
    pub const C_ACTIVE_ENERGY_MINUS_RATE3: u8 = 3,
    pub const C_ACTIVE_ENERGY_MINUS_RATE4: u8 = 4,
    pub const C_REACTIVE_ENERGY_PLUS_RATE1: u8 = 5,
    pub const C_REACTIVE_ENERGY_PLUS_RATE2: u8 = 6,
    pub const C_REACTIVE_ENERGY_PLUS_RATE3: u8 = 7,
    pub const C_REACTIVE_ENERGY_PLUS_RATE4: u8 = 8,
    pub const C_REACTIVE_ENERGY_MINUS_RATE1: u8 = 5,
    pub const C_REACTIVE_ENERGY_MINUS_RATE2: u8 = 6,
    pub const C_REACTIVE_ENERGY_MINUS_RATE3: u8 = 7,
    pub const C_REACTIVE_ENERGY_MINUS_RATE4: u8 = 8,
    pub const C_ACTIVE_DEMAND_PLUS: u8 = 1,
    pub const C_ACTIVE_DEMAND_MINUS: u8 = 2,
    pub const C_REACTIVE_DEMAND_PLUS: u8 = 3,
    pub const C_REACTIVE_DEMAND_MINUS: u8 = 4,
    pub const C_APPARENT_DEMAND: u8 = 9,

    pub const C_ACTIVE_DEMAND_PLUS_RATE1: u8 = 1,
    pub const C_ACTIVE_DEMAND_PLUS_RATE2: u8 = 2,
    pub const C_ACTIVE_DEMAND_PLUS_RATE3: u8 = 3,
    pub const C_ACTIVE_DEMAND_PLUS_RATE4: u8 = 4,

    // Group E: Further classification
    pub const E_TOTAL: u8 = 0,
    pub const E_RATE1: u8 = 1,
    pub const E_RATE2: u8 = 2,
    pub const E_RATE3: u8 = 3,
    pub const E_RATE4: u8 = 4,
    pub const E_TARIFF1: u8 = 1,
    pub const E_TARIFF2: u8 = 2,

    // Group F: Historical value / billing period
    pub const F_NOT_USED: u8 = 255;
    pub const F_CURRENT: u8 = 0;
    pub const F_PREVIOUS_1: u8 = 1;
    pub const F_PREVIOUS_2: u8 = 2;
    pub const F_PREVIOUS_3: u8 = 3;
    pub const F_PREVIOUS_4: u8 = 4;
    pub const F_PREVIOUS_5: u8 = 5;
    pub const F_PREVIOUS_6: u8 = 6;
    pub const F_PREVIOUS_7: u8 = 7;
    pub const F_PREVIOUS_8: u8 = 8;
    pub const F_PREVIOUS_9: u8 = 9;
    pub const F_PREVIOUS_10: u8 = 10;
    pub const F_PREVIOUS_11: u8 = 11;
    pub const F_PREVIOUS_12: u8 = 12;

